"""oligotox: OligoTox ML pipeline package."""
from .core import (
    BackboneClass,
    SugarModification,
    ToxicityEndpoint,
    Oligonucleotide,
    ToxicityRecord,
    FeatureVector,
    OligotoxPipeline,
    ToxicityPredictor,
    compute_gc_content,
    compute_cpg_ratio,
    compute_motif_score,
    extract_features,
)
from .evaluate import (
    aucroc,
    auroc_score,
    calibration_error,
    toxicity_profile_summary,
    model_comparison,
    endpoint_breakdown,
    feature_importance_summary,
)

__all__ = [
    "BackboneClass",
    "SugarModification",
    "ToxicityEndpoint",
    "Oligonucleotide",
    "ToxicityRecord",
    "FeatureVector",
    "OligotoxPipeline",
    "ToxicityPredictor",
    "compute_gc_content",
    "compute_cpg_ratio",
    "compute_motif_score",
    "extract_features",
    "aucroc",
    "auroc_score",
    "calibration_error",
    "toxicity_profile_summary",
    "model_comparison",
    "endpoint_breakdown",
    "feature_importance_summary",
]
